### ISSUE TITLE
Too many Issues/Warnings

### ISSUE THREAD

**Issue by reader-man** [xamarinhq/app-acquaint#15]
Hi,
Thanks for this Good example, but when i downloaded it, and re-built it, it got built correctly, but with 33 warnings, and i did not try to update the nuget libs, some of them:
Warning CS0618  'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.' Acquaint.XForms D:\4_Prj\Mobile Apps_Xamarin Apps\Acquaint\01 Acquaint- Before Updating nuget\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs    17  Active
Warning CS0618  'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.' Acquaint.XForms D:\4_Prj\Mobile Apps_Xamarin Apps\Acquaint\01 Acquaint- Before Updating nuget\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs    24  Active
Warning     Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. Acquaint.XForms.Droid   C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets 1820  
Warning     Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. Acquaint.XForms.iOS C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets 1820    

**and the remaining 33 warnings are in here:**
[A Before  XF Update - Warnings.txt](https://github.com/xamarinhq/app-acquaint/files/344509/A.Before.XF.Update.-.Warnings.txt)

**and the build output:**
[A Before  XF Update - Build Output.txt](https://github.com/xamarinhq/app-acquaint/files/344508/A.Before.XF.Update.-.Build.Output.txt)
[A Before  XF Update - Build Output.zip](https://github.com/xamarinhq/app-acquaint/files/344513/A.Before.XF.Update.-.Build.Output.zip)

and when updating the XF nuget to Xamarin.Forms, 
**the warnings rose to 53:**
[B Before  XF Update - Warnings.txt](https://github.com/xamarinhq/app-acquaint/files/344511/B.Before.XF.Update.-.Warnings.txt)

**and the build output:**
[B After  XF Update - Build Output.txt](https://github.com/xamarinhq/app-acquaint/files/344510/B.After.XF.Update.-.Build.Output.txt)
[B After  XF Update - Build Output.zip](https://github.com/xamarinhq/app-acquaint/files/344514/B.After.XF.Update.-.Build.Output.zip)

Last, It would be nice while fixing these issues, that all nuget libs, get updated to latest versions.

Regards.

**Comment by wyattblake** [comment]
Submit a full request with the fixes.

**Comment by jsauvexamarin** [comment]
Working on this and much more in the `azure-app-service` branch. Stay tuned.

**Comment by reader-man** [comment]
@jsauvexamarin Thanks, i'll be waiting.

**Comment by jsauvexamarin** [comment]
Merged all changes from azure-app-service to master months ago.
