### ISSUE TITLE
Android project doesn't build (VS 2015.3)

### ISSUE THREAD

**Issue by hardcodet** [xamarinhq/app-acquaint#19]
Updated VS with latest patches, but attempting to compile the `Acquaint.XForms.Droid`package doesn't work on my system (The `Acquaint.XForms `project builds). While I get rid of tons of initial errors by restarting VS after package restore, it trips over the AppCompat theme, which it cannot resolve. The Support.v7.AppCompat package is properly referenced and downloaded, and references seem to be ok, but no luck. See screenshots for errors before / after reload.

![errors_before_restart](https://cloud.githubusercontent.com/assets/873009/17904046/03d5a242-696e-11e6-9047-eb30c35d56cd.png)

![after_reload](https://cloud.githubusercontent.com/assets/873009/17904059/128da8c0-696e-11e6-858a-3bcb1947881b.png)

**Comment by jsauvexamarin** [comment]
This can happen when the download of Android support library zip files become corrupted, sometimes due to a connection error when downloading.

Try deleting the contents of `C:\Users\[your user]\AppData\Local\xamarin` (which is the location of the zips) and then rebuild.

**Comment by hardcodet** [comment]
Got it to build after wiping out the cache. Thanks!
