### ISSUE TITLE
Errors in build

### ISSUE THREAD

**Issue by ngmob** [xamarinhq/app-acquaint#2]
Hi!

After compiling the project I'm getting a lot of mistakes. Following is the list below:

--------

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'fab' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs	20	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\App.xaml	0	
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml	0	
Error	CS0103	The name 'AcquaintanceMap' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs	35	Active
Error	CS0103	The name 'AcquaintanceMap' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs	66	Active
Error	CS0103	The name 'AcquaintanceMap' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs	68	Active
Error	CS0103	The name 'AcquaintanceMap' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs	70	Active
Error	CS0103	The name 'AcquaintanceMap' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs	72	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceEditPage.xaml	0	
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml	0	
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs	13	Active
Error		Build action 'EmbeddedResource' is not supported by one or more of the project's targets.	Acquaint.XForms	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\Pages\SplashPage.xaml	0	
Error		'Resource.String' does not contain a definition for 'ApplicationName'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	29	
Error		'Resource.String' does not contain a definition for 'Hello'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	30	
Error		'Resource.Attribute' does not contain a definition for 'fab_colorDisabled'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	31	
Error		'Resource.Attribute' does not contain a definition for 'fab_colorNormal'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	32	
Error		'Resource.Attribute' does not contain a definition for 'fab_colorPressed'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	33	
Error		'Resource.Attribute' does not contain a definition for 'fab_colorRipple'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	34	
Error		'Resource.Attribute' does not contain a definition for 'fab_shadow'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	35	
Error		'Resource.Attribute' does not contain a definition for 'fab_size'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	36	
Error		'Resource.Color' does not contain a definition for 'fab_material_blue_500'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	41	
Error		'Resource.Dimension' does not contain a definition for 'fab_elevation_lollipop'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	42	
Error		'Resource.Dimension' does not contain a definition for 'fab_scroll_threshold'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	43	
Error		'Resource.Dimension' does not contain a definition for 'fab_shadow_size'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	44	
Error		'Resource.Dimension' does not contain a definition for 'fab_size_mini'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	45	
Error		'Resource.Dimension' does not contain a definition for 'fab_size_normal'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	46	
Error		'Resource.Drawable' does not contain a definition for 'fab_shadow'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	48	
Error		'Resource.Drawable' does not contain a definition for 'fab_shadow_mini'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	49	
Error		'Resource.Styleable' does not contain a definition for 'FloatingActionButton_fab_colorDisabled'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	54	
Error		'Resource.Styleable' does not contain a definition for 'FloatingActionButton_fab_colorNormal'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	55	
Error		'Resource.Styleable' does not contain a definition for 'FloatingActionButton_fab_colorPressed'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	56	
Error		'Resource.Styleable' does not contain a definition for 'FloatingActionButton_fab_colorRipple'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	57	
Error		'Resource.Styleable' does not contain a definition for 'FloatingActionButton_fab_shadow'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	58	
Error		'Resource.Styleable' does not contain a definition for 'FloatingActionButton_fab_size'	Acquaint.XForms.Droid	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.Droid\Resources\Resource.designer.cs	59	
Error		Metadata file 'D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms\bin\Debug\Acquaint.XForms.dll' could not be found	Acquaint.XForms.UWP	D:\Trabalho\Estudos\Xamarin\app-acquaint-master\app-acquaint-master\Acquaint.XForms\Acquaint.XForms.UWP\CSC		

--------

I analyzed the previous issue and my VS settings are ok.

What is the cause of these errors?

Thanks!

ngmob

**Comment by ngmob** [comment]
I forgot to mention. I am compiling a solution Acquaint.XForms.

**Comment by snowstormlife** [comment]
NGmob: Get preview Nuget packages for Xamarin.Forms and Xamarin.Forms.Maps. Also make a change to your Android project's .csproj file to help prevent aapt.exe from becoming a CPU hog.

See 
BUG LOGGED IN BUGZILLA:
https://bugzilla.xamarin.com/show_bug.cgi?id=33181

The real fix for now: Install one of these:
	Brendan Zagaeski 2016-04-25 05:52:09 UTC 
	## Verification status: verified fixed on Xamarin.Forms 2.2.0.5-pre2 and 2.2.0.23-pre4 (available on NuGet)
	GOOD: Xamarin.Forms 2.2.0.23-pre4
GOOD: Xamarin.Forms 2.2.0.5-pre2
BAD:  Xamarin.Forms 2.1.0.6529
	As hinted at in Comment 43, there is one subtle, fairly uncommon situation where the default behavior for this issue in the "GOOD" versions might still occasionally cause some confusion or inconvenience. I have filed a separate in-depth follow-up bug report about that situation: Bug 40666.

And see https://forums.xamarin.com/discussion/62703/visual-studio-2015-unresponsive-at-build-time-aapt-hogging-the-cpu

I managed to solve this - every time a Nuget Package was added to my Xamarin.Forms Android app, aapt.exe would peg the CPU at 100% to crunch every PNG asset. Once you have a load of assets this would take ages, for every build.

A work around is to edit your csproj file and add
<AndroidResgenExtraArgs>--no-crunch</AndroidResgenExtraArgs>

to the Debug Property Group. This skips the PNG crunching in aapt.exe and speeds up debug builds considerably."

**Comment by jsauvexamarin** [comment]
Thank you for your feedback. I'll be looking at this later today.

**Comment by jsauvexamarin** [comment]
@ngmob: Have you selected the correct config and platform combination from the Visual Studio toolbar? You need to select a platform architecture that is appropriate for the particular platform you are trying to build. You also need to set the correct project to be the Startup Project.

1.
Right-click either the Acquaint.XForms.iOS project or Acquaint.XForms.Droid project, and select "Set as Startup Project" from the context menu.

2.
If you've set iOS as the startup project, make sure the platform drop-down is set to "iPhone" or "iPhoneSimulator". For Android, you can set the platform to "Any CPU".

3.
Build the project, by either starting debugging or plainly building the project via the Build menu.

These are very beginner suggestions for solving common errors like you're seeing. I apologize if I'm incorrectly assuming you're new to Xamarin development. If these steps don't remedy your problem, please back.

**Comment by jsauvexamarin** [comment]
@snowstormlife: The solution has been updated to Forms 2.2 stable. Thanks for the `--no-crunch` tip! I was unaware of that. Very interesting and helpful.

**Comment by ngmob** [comment]
Hi!

Thanks for the help **@snowstormlife** and **@jsauvexamarin**!

The steps to set the start project and the platform I ran when I tried to run the example.

I made the following way now:
    1) Download of the new version of the source code
    2) Start-up project settings
    3) Build and run.

The example worked normally.

Thank you very much for the help!!

Thanks!

ngmob
