### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by DasAllFolks** [xamarinhq/app-acquaint#25]
Hey guys,

Thanks for putting together [this and other great demo apps](https://www.xamarin.com/prebuilt) for Xamarin!

Just checking:  are all four of these demo repos MIT licensed?

It looks like this is the case, but the licensing information seems to be scattered in different places in each of these repos (rather than located at the root directory, like I've seen in a lot of other GitHub projects).

Thanks in advance for your help!

-Steven

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
