### ISSUE TITLE
Unhandled Exception:  Android.Views.InflateException: Error inflating class EditText

### ISSUE THREAD

**Issue by nok91** [xamarinhq/app-acquaint#39]
SetupActivity.cs - Device: Samsung SM-N9005(Android 5.0 - API21)

Unhandled Exception:

Android.Views.InflateException: Binary XML file line #1: Error inflating class EditText occurred

**Comment by jsauvexamarin** [comment]
Are you only seeing this with API level 21?

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
