### ISSUE TITLE
AcquaintanceListViewModel.cs - Adding emty list of items will throw an exception on UWP

### ISSUE THREAD

**Issue by janoratowski** [xamarinhq/app-acquaint#4]
On line 92 of AcquaintanceListViewModel.cs there is:

`Acquaintances.AddRange (acquaintances);`

While it works perfectly on any platform if acquaintances.Count!=0, it will also throw an exception (only) on UWP, if acquaintances.Count==0.

To safeguard against that, the code should be changed to:

`if (acquaintances.Count!=0) Acquaintances.AddRange (acquaintances);`

**Comment by jsauvexamarin** [comment]
Thx! If it all tests out well, I'll commit an update today.
