### ISSUE TITLE
Warnings in solution

### ISSUE THREAD

**Issue by reader-man** [xamarinhq/app-acquaint#41]
Hi,
Thanks for the great working demo app.

But the following are showing:

**Build Output:**

7>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Common\Acquaint.Data\FilesystemOnlyAcquaintanceDataSource.cs(39,56,39,71): warning CS0067: The event 'FilesystemOnlyAcquaintanceDataSource.OnDataSyncError' is never used
7>  Acquaint.Data -> D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Common\Acquaint.Data\bin\Debug\Acquaint.Data.dll
8>------ Rebuild All started: Project: Acquaint.XForms, Configuration: Debug Any CPU ------
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(44,34,44,36): warning CS0168: The variable 'ex' is declared but never used
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(17,69,17,158): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(24,71,24,160): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(31,72,31,162): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(38,71,38,160): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(45,64,45,185): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(52,69,52,148): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'

**Warnings in Error List**

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	Acquaint.XForms.Droid			
Warning	CS0168	The variable 'ex' is declared but never used	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs	44	Active
Warning	CS0618	'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs	17	Active
Warning	CS0618	'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs	24	Active
Warning	CS0618	'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs	31	Active
Warning	CS0618	'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs	38	Active
Warning	CS0618	'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs	45	Active
Warning	CS0618	'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'	Acquaint.XForms	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs	52	Active
Warning		Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>	Acquaint.XForms.Droid			
Warning	CS0067	The event 'FilesystemOnlyAcquaintanceDataSource.OnDataSyncError' is never used	Acquaint.Data	D:\4_Prj\Apps\_Xamarin Apps\Acquaint\App\Common\Acquaint.Data\FilesystemOnlyAcquaintanceDataSource.cs	39	Active

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
