### ISSUE TITLE
UI issues on pre-material design devices

### ISSUE THREAD

**Issue by karlcod531** [xamarinhq/app-acquaint#43]
When the app is deployed on devices having an OS that is pre-material design (tested on Android 4.4), I ma encountering a few issues with the UI:
1) EditTexts have smudged edges
2) toolbar buttons have black edges when clicked

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
