### ISSUE TITLE
packages are not updated.

### ISSUE THREAD

**Issue by dengere** [xamarinhq/app-acquaint#44]
projects need 43 updates, 13 consolidates(!). Its look like  need strongly nuget package update.

**Comment by dengere** [comment]
Projects used many obsoloted members. Really someone care?

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
