### ISSUE TITLE
change Microsoft Azure to normal REST API 

### ISSUE THREAD

**Issue by engsafory** [xamarinhq/app-acquaint#45]
I am trying to migratie this solution from feeding from Microsoft Azure to Normal Rest API that i will create it by PHP , but who to start to change this integration ?

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
