### ISSUE TITLE
Build fails on freshly downloaded code with VS2017

### ISSUE THREAD

**Issue by prinkpan** [xamarinhq/app-acquaint#49]
Thank you for taking the efforts and sharing your code.

I am struggling to build it in my VS2017 environment. I have set Acquaint.XForms.Droid as my start-up project. I am getting the following error while building it.

The "ValidatePackageReferences" task could not be loaded from the assembly C:\Xamarin\app-acquaint-master\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll. Could not load file or assembly 'file:///C:\Xamarin\app-acquaint-master\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask in Acquaint.Data

The "ValidatePackageReferences" task could not be loaded from the assembly C:\Xamarin\app-acquaint-master\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll. Could not load file or assembly 'file:///C:\Xamarin\app-acquaint-master\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask in Acquaint.XForms.Droid

Appreciate your help.

**Comment by steviehutch** [comment]
Hi Prinkpan, have you resolved your issue yet? I had the same problems as you, but managed to resolve them by installing Microsoft.Bcl package in the Acquaint.XForms project using Nuget. Then the errors regarding Microsoft.Bcl went away.
Kind Regards
StevieHutch

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
