### ISSUE TITLE
Visual STUDIO Team Services issue

### ISSUE THREAD

**Issue by IsmaelKP** [xamarinhq/app-acquaint#5]
Hi, 

First of all thank you for this sample which is really complete from a new user point of View. 

I am trying to implement the build of the project Visual Studio Team Services for Continious Integration. 
I get some issue on build result. (I looked at the others closed issues but didnt find my problem)

Here is my workflow : 

![image](https://cloud.githubusercontent.com/assets/4320318/15679696/10e628b0-2753-11e6-8386-63fb07c383db.png)

I get the following error:

![image](https://cloud.githubusercontent.com/assets/4320318/15679858/b72aebac-2753-11e6-9430-b6f512a55ecb.png)

There is some french in the error message but the issue is on a the package:
**..\..\packages\Xamarin.Forms.2.1.0.6529\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.targets**

**Comment by jsauvexamarin** [comment]
Hi @IsmaelKP, I'm really glad that you find the Acquaint sample app to be helpful.

What are you using as your VSTS build agent?: MacInCloud? vso-agent? vsts-agent?

I've recently begun using vsts-agent on my local Mac Mini as my VSTS agent. My build workflow only contains two steps: the iOS build and the Android build. You shouldn't need to manually restore the NuGet packages; this is done for automatically in the build. Also, if you'e using a local build agent, you shouldn't need the Xamarin license activation steps either.

You can find vsts-agent here: 
https://github.com/Microsoft/vsts-agent

The releases:
https://github.com/Microsoft/vsts-agent/releases

My simple workflow looks like this and works great:
![](http://s33.postimg.org/oymiwowhp/VSTS_OSX_agent.png)

**Comment by IsmaelKP** [comment]
Hi, 

Thank you for the quick reply, 

I tried to implement your solution. I was interrested first by setting up the Android Build. I do have a MacIncloud Dedicated server but I want to try first on my own computer. 

I configure the vsts-agent to do so. agent is running perfect I do get an error though on Invoke-msbuild

![image](https://cloud.githubusercontent.com/assets/4320318/15714843/7c1fcdba-281c-11e6-9f36-9a62fc8be7de.png)

Basically it says Invoke-msbuild is not recognize as a command.
did you came accross this kind of error?
 When I added the package Invoke-msbuild to the solution using Package Manager on Visual Studio 2015.

I also added msbuild to path environment variables to make sure it can be called
![image](https://cloud.githubusercontent.com/assets/4320318/15715190/d08cd6c6-281d-11e6-8cca-62a18030e816.png)

Hope you can help me on this one otherwise I will use the MacInCloud server.

**Comment by jsauvexamarin** [comment]
@IsmaelKP, I have not encountered this error. If you're getting msbuild errors, then it seems you're trying to build the Android app on a Windows machine. I'm building both my iOS and Android apps on a single Mac that's running the vsts-agent, so I use xbuild instead of msbuild.

For specific questions about the agent, you'll need to ask the vsts-agent team: https://github.com/Microsoft/vsts-agent/issues

**Comment by jsauvexamarin** [comment]
Closing, due to the issues being related to CI and VSTS, not the Acquaint source code.
