### ISSUE TITLE
Impossible to get this project to run

### ISSUE THREAD

**Issue by cappaulo** [xamarinhq/app-acquaint#50]
Downloaded the zip. Ran the solution file(s) but now I'm stuck at https://developer.xamarin.com/guides/android/troubleshooting/resolving-library-installation-errors/

Still, even after manually trying to install the library I get stuck with some other issue.

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
