### ISSUE TITLE
Even after making necessary code changes so that app builds, it crashes when run on iOS emulator

### ISSUE THREAD

**Issue by steviehutch** [xamarinhq/app-acquaint#51]
So i have made the necessary NuGet updates. I am running Visual Studio 2017 Professional ( with version 15.6.2 update ), on Windows 10 and have a remote Mac building the iOS code.
I have managed to get this to build, but when run, i get this error ..

Unhandled Exception:

Xamarin.Forms.Xaml.XamlParseException: Position 39:15. Type fftransformations:CircleTransformation not found in xmlns clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations

( p.s. I am running Acquaint Xamarin Forms version not the native version )

**Comment by tr0yspradling** [comment]
I got the exact same error. I'm on OSX 10.14.2 using Visual Studio to develop, and iOS 12 simulators.

**Comment by daniel-luberda** [comment]
just put `new CircleTransformation()` somewhere in your platform specific project. It's a linker issue.

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
