### ISSUE TITLE
https://app-acquaint.azurewebsites.net is down

### ISSUE THREAD

**Issue by cosminstirbu** [xamarinhq/app-acquaint#54]
Hello,

It seems the backend is down - https://app-acquaint.azurewebsites.net.

`Failure | UnknownHost: app-acquaint.azurewebsites.net: nodename nor servname provided, or not known`

Can you please look into it?

Thank you,
Cosmin

**Comment by jsauve** [comment]
I'm not sure this app is maintained on a regular basis anymore. I originally built it, but I left MSFT a couple years ago. It was difficult to convince some colleagues at the time that we ought to keep samples up to date all times. Nothing against them personally; it was more of an organizational issue. It was just that samples weren't treated like first-class apps, and I have very strong opinions that they should be, with full CI and maintenance cycles around them. Unfortunately, that's just not the case.

If I personally had time to maintain this sample or I was compensated to do so, I certainly would, but my contracting gig keeps me very busy. The repo is likely left in place by MSFT as a legacy reference. Honestly, there's TONS about this code base that needs to be improved to make it on par with modern app architecture.

**Comment by LutherOne** [comment]
Do you know where I can find another similar sample app that is on par with modern app architecture?

**Comment by jsauve** [comment]
I'm not sure, unfortunately. I created this because there was nothing like it at the time that demonstrated the Forms vs platform way of doing Xamarin apps. There may be some other samples out there somewhere, but I'm not aware of them.

**Comment by LutherOne** [comment]
Hello Joe,

 

Thanks!!!

**Comment by jamesmontemagno** [comment]
This sample has officially been deprecated and replaced with the "[My Contacts](https://github.com/xamarin/app-contacts)" sample application that showcases Xamarin.Forms and an ASP.NET Core backend.
